### ISSUE TITLE
Insufficient memory reserved for statement

### ISSUE THREAD

**Issue by aksh-4793** [pivotalguru/TPC-DS#6]
When I run the script, the 4th query ( 104.tpcds.04.sql ) throws me the following error:

psql: TPC-DS/05_sql/104.tpcds.04.sql:115: ERROR:  insufficient memory reserved for statement
HINT:  Increase statement memory or reduce the number of Parquet tables to be scanned.

**Comment by RunningJon** [comment]
How much memory do you have in each node of your cluster?  How much ram is used for other processes? How much swap do you have?  How much memory do you have allocated to hawq?  What is the over commit value and ratio?   

This error is caused by a memory configuration problem in hawq and not in the query.  

Jon Roberts

**Comment by aksh-4793** [comment]
I have setup 4 nodes 1 master and 3 segments on Ubuntu
The slaves have about 128GB RAM

The parameters I have set in HAWQ GUC are as follows:
hawq_re_memory_overcommit_max : 98304
hawq_rm_stmt_vseg_memory : 16gb

In my kernel parameters I have overcommit ratio as 80

Let me know if I need to specify anything else.

**Comment by RunningJon** [comment]
Change the hawq_rm_stmt_vseg_memory to the default of 128mb.

Do you have swap?  You should have 4GB of swap.

hawq_rm_memory_limit_perseg sholud be set to 120 or a bit lower if you have
a lot of other processes going on these nodes.

Overcommit ratio should be 100 because you have 128GB of RAM.
